import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = path.join(root, 'www');
const functionsDir = path.join(root, 'functions');

function walk(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = path.join(directory, entry.name);
    return entry.isDirectory() ? walk(fullPath) : [fullPath];
  });
}

function cspHash(value) {
  const digest = crypto.createHash('sha256').update(value).digest('base64');
  return `'sha256-${digest}'`;
}

const sourceFiles = walk(publicDir).filter((file) => {
  return /\.(html|js)$/i.test(file) && path.basename(file) !== 'supabase.js';
});

const eventHandlers = new Set();
const inlineScripts = new Set();

for (const file of sourceFiles) {
  const contents = fs.readFileSync(file, 'utf8');

  for (const match of contents.matchAll(/\bon[a-z]+\s*=\s*(["'])(.*?)\1/gs)) {
    eventHandlers.add(match[2]);
  }

  if (file.endsWith('.html')) {
    for (const match of contents.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)) {
      inlineScripts.add(match[1]);
    }
  }
}

const scriptHashes = [...eventHandlers, ...inlineScripts]
  .map(cspHash)
  .sort()
  .join(' ');

const csp = [
  "default-src 'self'",
  `script-src 'self' 'unsafe-hashes' ${scriptHashes}`,
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data: blob: https://images.unsplash.com https://via.placeholder.com",
  "media-src 'self' blob:",
  "connect-src 'self' https://idpwlfgicadaeqakhkqa.supabase.co wss://idpwlfgicadaeqakhkqa.supabase.co",
  "frame-src https://www.youtube-nocookie.com",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

const middleware = `// Generated by tools/generate-headers.mjs. Do not edit manually.
const CONTENT_SECURITY_POLICY = ${JSON.stringify(csp)};

export async function onRequest(context) {
  const assetResponse = await context.next();
  const response = new Response(assetResponse.body, assetResponse);

  response.headers.set('Content-Security-Policy', CONTENT_SECURITY_POLICY);
  response.headers.set('Strict-Transport-Security', 'max-age=31536000; includeSubDomains; preload');
  response.headers.set('X-Content-Type-Options', 'nosniff');
  response.headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
  response.headers.set('Permissions-Policy', 'camera=(), microphone=(), geolocation=(), payment=(), usb=()');
  response.headers.set('Cross-Origin-Opener-Policy', 'same-origin');
  response.headers.set('X-Frame-Options', 'DENY');

  if (new URL(context.request.url).pathname.startsWith('/assets/')) {
    response.headers.set('Cache-Control', 'public, max-age=604800, stale-while-revalidate=86400');
  }

  return response;
}
`;

fs.mkdirSync(functionsDir, { recursive: true });
fs.writeFileSync(path.join(functionsDir, '_middleware.js'), middleware, 'utf8');
fs.rmSync(path.join(publicDir, '_headers'), { force: true });
console.log(`Generated functions/_middleware.js with ${eventHandlers.size} event-handler hashes.`);
